In [5]:
import numpy as np

# Example data for two variables
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

# Calculate the mean of x and y
mean_x = np.mean(x)
mean_y = np.mean(y)

# Calculate the covariance
covariance = np.sum((x - mean_x) * (y - mean_y)) / (len(x) - 1)

print("Covariance:", covariance)


Covariance: -2.5


Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium,
large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library.
Show your code and explain the output.

Ans:-

To perform label encoding using the scikit-learn library in Python, you can use the LabelEncoder class from the sklearn.preprocessing module. Here's the code:

In [2]:
from sklearn.preprocessing import LabelEncoder

# Sample data
colors = ['red', 'green', 'blue', 'red', 'green']
sizes = ['small', 'medium', 'large', 'medium', 'small']
materials = ['wood', 'metal', 'plastic', 'metal', 'wood']

# Initialize label encoders
color_encoder = LabelEncoder()
size_encoder = LabelEncoder()
material_encoder = LabelEncoder()

# Fit and transform the data
encoded_colors = color_encoder.fit_transform(colors)
encoded_sizes = size_encoder.fit_transform(sizes)
encoded_materials = material_encoder.fit_transform(materials)

print("Encoded Colors:", encoded_colors)
print("Encoded Sizes:", encoded_sizes)
print("Encoded Materials:", encoded_materials)


Encoded Colors: [2 1 0 2 1]
Encoded Sizes: [2 1 0 1 2]
Encoded Materials: [2 0 1 0 2]


In [3]:
import numpy as np

# Sample data
age = [25, 30, 35, 40, 45]
income = [50000, 60000, 75000, 90000, 100000]
education_level = [1, 2, 2, 3, 3]  # Assuming: 1 = High School, 2 = Bachelor's, 3 = Master's/PhD

# Stack the variables to create a 2D array
data = np.stack((age, income, education_level), axis=0)

# Calculate the covariance matrix
covariance_matrix = np.cov(data)

print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[ 6.25e+01 -6.25e+03  6.25e+00]
 [-6.25e+03  9.20e+06 -1.75e+02]
 [ 6.25e+00 -1.75e+02  7.00e-01]]
